apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: newrelic-php
  name: newrelic-php
spec:
  replicas: 1
  selector:
    matchLabels:
      run: newrelic-php
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: newrelic-php
    spec:
      containers:
      - image: ntfrnzn/newrelic-php
        imagePullPolicy: Always
        name: newrelic-php-agent
        env:
        - name: NEWRELIC_PHP_LICENSE
          valueFrom:
            secretKeyRef:
              name: newrelic-php
              key: license_key
        - name: NEWRELIC_PHP_APPNAME
          value: urticina
        - name: NEWRELIC_PHP_LOGLEVEL
          value: verbosedebug
        - name: NEWRELIC_PHP_LOGFILE
          value: /var/log/newrelic/php_agent.log
        ports:
        - containerPort: 9000
          protocol: TCP
        resources: {}
      - image: ntfrnzn/newrelic-php
        imagePullPolicy: Always
        name: newrelic-php-daemon
        command:
          - /usr/bin/newrelic-daemon
          - -f
          - -c
          - /etc/newrelic/newrelic.cfg
        ports:
        - containerPort: 33142
          protocol: TCP
        resources: {}
        volumeMounts:
        - name: daemon-config
          mountPath: /etc/newrelic/
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: daemon-config
          configMap:
            name: newrelic-daemon
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
